// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6ZGCIi-Y6fvOrdmVaCsVOefqRE0CL90Q',
    appId: '1:61156491550:web:f241a116ffc240c6d8090f',
    messagingSenderId: '61156491550',
    projectId: 'code-dc-2e246',
    authDomain: 'code-dc-2e246.firebaseapp.com',
    storageBucket: 'code-dc-2e246.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvw8B1Im_WcJeEbRB2Rag6ABPM2k05qZI',
    appId: '1:61156491550:android:11056ffdbd31fbc6d8090f',
    messagingSenderId: '61156491550',
    projectId: 'code-dc-2e246',
    storageBucket: 'code-dc-2e246.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAntf65LHjJinzath386DPwreVpRky4N3Y',
    appId: '1:61156491550:ios:fdda2a357f709a12d8090f',
    messagingSenderId: '61156491550',
    projectId: 'code-dc-2e246',
    storageBucket: 'code-dc-2e246.appspot.com',
    iosClientId: '61156491550-fvqs0ibb9vn082vlfk80u41e2vn3p7nd.apps.googleusercontent.com',
    iosBundleId: 'com.CODEDC.CODEDCAPP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAntf65LHjJinzath386DPwreVpRky4N3Y',
    appId: '1:61156491550:ios:fdda2a357f709a12d8090f',
    messagingSenderId: '61156491550',
    projectId: 'code-dc-2e246',
    storageBucket: 'code-dc-2e246.appspot.com',
    iosClientId: '61156491550-fvqs0ibb9vn082vlfk80u41e2vn3p7nd.apps.googleusercontent.com',
    iosBundleId: 'com.CODEDC.CODEDCAPP',
  );
}
